### ISSUE TITLE
Add code files for sorting algorithms as mentioned in Readme.md

### ISSUE THREAD

**Issue by King14844** [King14844/Famous-Algorithms#1]
Please add code files for sorting algorithms as mentioned in Readme.md

**Comment by Adi-456** [comment]
please assign this issue to me.

**Comment by Upendra2003** [comment]
Assign me this I can do this.

**Comment by Karanjamwal21** [comment]
It's my first time on open source. I would like to do this assignment.

**Comment by King14844** [comment]
Just fork the repo and submit PR

**Comment by Karanjamwal21** [comment]
I had done the work.
