### ISSUE TITLE
Implement all the Divide and Conquer algorithms present in Readme.md

### ISSUE THREAD

**Issue by King14844** [King14844/Famous-Algorithms#3]
Implement all the Divide and Conquer algorithms present in Readme.md
# Steps to do this
1. Fork this repository to your account
2. Clone the created repository to your local computer
3. Create a new branch with the relevant name
4. Implement as mentioned in the title
5. Push changes to your forked repository
6. Submit a Pull Request (PR) and wait for the approval.

**Comment by Karanjamwal21** [comment]
I would like to do this work.

**Comment by King14844** [comment]
Proceed with given steps.

**Comment by Karanjamwal21** [comment]
Thank you for assigning the work

**Comment by Karanjamwal21** [comment]
The work was done.

**Comment by King14844** [comment]
Merged it, the issue is closed now.
