### ISSUE TITLE
Make the documentation clear

### ISSUE THREAD

**Issue by King14844** [King14844/Famous-Algorithms#6]
1. Update the readme file with relevant new algorithms in each section.
2. Make the directory well-structured with relative algorithms under their own directory.

**Comment by MeetThakur** [comment]
assign me I'll do it

**Comment by King14844** [comment]
No need to assign, just follow the below steps,

1. Fork this repository to your account
2. Clone the created repository to your local computer
3. Create a new branch with the relevant name
4. Implement as mentioned in the title
5. Push changes to your forked repository
6. Submit a Pull Request (PR) and wait for the approval.

**Comment by MeetThakur** [comment]
okay , on it

**Comment by Arcturus22** [comment]
@King14844 
What exactly do you mean by update the readme file?
All the algorithms and divide and conquer codes which are there in the repo are mentioned in the Readme as well.
